### ISSUE TITLE
Doesn't work with ConfigWatcher

### ISSUE THREAD

**Issue by PrincessRTFM** [ASharpPen/Valheim.SpawnThat#107]
According to the [ConfigWatcher dev](https://github.com/blaxxun-boop/ConfigWatcher/issues/1) the issue is with SpawnThat using the BIE config system "in the wrong way" somehow. I don't know the details, so I'm just reporting what I know.

Original issue text, copied here for easier reference:

> I can't start a world, single- or multi-player. I can select my character, but at the screen where I choose the world to open, the start button doesn't work. The console reports this error trace:
>
> ```
> [Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: C:\Users\[REDACTED]\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Default\BepInEx\config\spawn_that.cfg
> Stack trace:
> System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
> System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
> ConfigWatcher.ConfigWatcher.initFileWatcher (System.WeakReference`1[T] configFileRef) (at <c7c726f0f48744cb8498386318b604d3>:0)
> ConfigWatcher.ConfigWatcher+Patch_ConfigFile_Constructor.Postfix (BepInEx.Configuration.ConfigFile __instance) (at <c7c726f0f48744cb8498386318b604d3>:0)
> (wrapper dynamic-method) BepInEx.Configuration.ConfigFile.DMD<BepInEx.Configuration.ConfigFile::.ctor>(BepInEx.Configuration.ConfigFile,string,bool,BepInEx.BepInPlugin)
> BepInEx.Configuration.ConfigFile..ctor (System.String configPath, System.Boolean saveOnInit) (at <be164cbbe0a546c59eda05037ff079c2>:0)
> Valheim.SpawnThat.Configuration.ConfigurationManager.LoadGeneral () (at <535ba01d739348f9b4aace59d56386bd>:0)
> Valheim.SpawnThat.Configuration.ConfigurationManager.LoadAllConfigurations () (at <535ba01d739348f9b4aace59d56386bd>:0)
> Valheim.SpawnThat.Reset.WorldStartupResetPatch.ResetState () (at <535ba01d739348f9b4aace59d56386bd>:0)
> (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::OnWorldStart>(FejdStartup)
> UnityEngine.Events.InvokableCall.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
> UnityEngine.Events.UnityEvent.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
> UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
> UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
> UnityEngine.EventSystems.EventSystem:Update()
> ```

**Comment by ASharpPen** [comment]
Thank you for the report :)

Sadly this is an incompatibility that I warned the author of a month ago. In short terms, there is nothing I can or will do about it. It is unfortunate you were directed here (or more specifically, keep getting redirected), but the error stems from ConfigWatchers assumptions and error handling.

While I do use the BepInEx configuration loading in a different manner than most mods, it is not broken and is essentially harmless. But ConfigWatcher injects itself in a way that I can do nothing to avoid, short of building in counter measures to disable it.
While the idea of updating configs on the fly is nice, it requires a lot more work and thought than just asking the default loader to run again. It's just not that simple.

**Comment by PrincessRTFM** [comment]
Ah well. Thanks anyway!
