### ISSUE TITLE
SpawnSystem.m_spawners not found

### ISSUE THREAD

**Issue by Voidheart** [ASharpPen/Valheim.SpawnThat#117]
```
[Error  : Unity Log] MissingFieldException: Field 'SpawnSystem.m_spawners' not found.
Stack trace:
(wrapper dynamic-method) SpawnSystem.DMD<SpawnSystem::UpdateSpawnList>(SpawnSystem,System.Collections.Generic.List`1<SpawnSystem/SpawnData>,System.DateTime,bool)
SpawnSystem.UpdateSpawning () (at <0b427da81d26480c885ae3fba0ed94c4>:0)

[Error  : Unity Log] MissingFieldException: Field 'SpawnSystem.m_spawners' not found.
Stack trace:
(wrapper dynamic-method) SpawnSystem.DMD<SpawnSystem::UpdateSpawnList>(SpawnSystem,System.Collections.Generic.List`1<SpawnSystem/SpawnData>,System.DateTime,bool)
SpawnSystem.UpdateSpawning () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
```

**Comment by ASharpPen** [comment]
Update your mods. That appears when a mod is trying to get the spawners from pre valheim 0.205.5. 
If Spawn That is not updated, it will be named in the stack-trace, so its something else that is broken.

**Comment by Voidheart** [comment]
Using DnSpy to search for SpawnSystem being used.. only SpawnThat! is using SpawnSystem and m_spawners

**Comment by ASharpPen** [comment]
Spawn That would still be generating a stack trace with it's name in it. 0.205.5 broke all mods using SpawnSystem.m_spawners completely, so I know what the error looks like.
Whatever issue you are having is not present in current versions.

**Comment by Voidheart** [comment]
I actually found the culprit I thought I would come and let you know, it turned out it was an addon that's not even on the ThunderStore.io its mod called Bears.dll it was patching the SpawnSystem compiled against old Assemblies
