### ISSUE TITLE
Does SpawnThat require an update for the Mistlands?

### ISSUE THREAD

**Issue by FelipeCardona95** [ASharpPen/Valheim.SpawnThat#172]
Title of the issue :D

**Comment by ASharpPen** [comment]
Yes. I expect to release a patch later today.

Until then, you can try out the pre-release build that was made for the public test branch: https://github.com/ASharpPen/Valheim.SpawnThat/releases

**Comment by FelipeCardona95** [comment]
Sweet I suppose is the same case for drop that :D

**Comment by ASharpPen** [comment]
No, Drop That seemed to be fine for now, although Epic Loot integration is probably broken right now. Fixing that will have to wait for Epic Loot to update though.

If I missed something, feel free to poke me :)
