### ISSUE TITLE
Error Message spam during World join

### ISSUE THREAD

**Issue by SenZ01** [ASharpPen/Valheim.SpawnThat#196]
[Error  : Unity Log] MissingMethodException: Method not found: Heightmap/Biome .Heightmap.GetBiome(UnityEngine.Vector3)
Stack trace:
SpawnThat.World.Zone.ZoneManager+PatchHeightmap.Record (Heightmap __instance) (at <65a661c0f3244c948ac9b1cd5c7bc22d>:0)
(wrapper dynamic-method) Heightmap.DMD<Heightmap::Regenerate>(Heightmap)
TerrainLod.RebuildHeightmap (TerrainLod+HeightmapWithOffset heightmapWithOffset) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
TerrainLod.RebuildAllHeightmaps () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
TerrainLod.UpdateHeightmaps () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
TerrainLod.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

New Ashlands Update
This is getting spammed in console

**Comment by ASharpPen** [comment]
Fix being worked on 👍
