### ISSUE TITLE
bug: duplicate world spawner ID

### ISSUE THREAD

**Issue by nbusseneau** [ASharpPen/Valheim.SpawnThat#200]
Hello, thanks a lot for your mods :)

I noticed an issue which I believe was introduced by #198 / 1.2.12 (the world spawner ID fix): it is now possible to have third-party spawners with duplicate IDs.

### Minimal reproduction setup

- Valheim 0.218.15 (Ashlands)
- Spawn That 1.2.13
- [MonsterLabZ](https://thunderstore.io/c/valheim/p/MonsterLabZ/MonsterLabZ/) 3.0.9
- The following `spawn_that.world_spawners.duplicateIdExample.cfg` config file:
  ```
  [WorldSpawner.60]
  Enabled=False
  ```

### Expected

- Vanilla `WorldSpawner.60` (`Seeker defeated queen other biomes`) is disabled.

### Observed

- Vanilla `WorldSpawner.60` (`Seeker defeated queen other biomes`) is still enabled.
- Another `WorldSpawner.60` (`EvilShadow`) exists later down in the file, and is the one getting disabled. This is a spawner introduced as part of `MonsterLabZ`'s creatures, via [CreatureManager](https://github.com/blaxxun-boop/CreatureManager).

### Analysis

Pre- and post-changes logs: [spawn_that.world_spawners_pre_changes.txt](https://github.com/user-attachments/files/15525860/spawn_that.world_spawners_pre_changes.txt) [spawn_that.world_spawners_post_changes.txt](https://github.com/user-attachments/files/15525861/spawn_that.world_spawners_post_changes.txt)

- Pre-changes everything looks good, there are no duplicate IDs.
- Post-changes it seems all MonsterLabZ world spawners IDs have been changed, and they are now conflicting with the vanilla IDs. For example here `EvilShadow` is `WorldSpawner.89` pre-changes and becomes `WorldSpawner.60` post-changes.

If we revert Spawn That to 1.2.11 (right before the world spawner ID fix), there are no conflicting IDs.
Pre- and post-changes logs: [spawn_that.world_spawners_pre_changes.txt](https://github.com/user-attachments/files/15525883/spawn_that.world_spawners_pre_changes.txt) [spawn_that.world_spawners_post_changes.txt](https://github.com/user-attachments/files/15525885/spawn_that.world_spawners_post_changes.txt)

- `EvilShadow` is assigned `WorldSpawner.60` and keeps it post-changes.
- Vanilla `Seeker defeated queen other biomes` gets assigned `WorldSpawner.118`.

At a glance it feels like for some reason the processing does not use the updated / fixed world spawners ID, and still uses the old pre-fix IDs somehow (because as we can see, `WorldSpawner.60` was indeed the ID assigned to `EvilShadow` in 1.2.11).

**Comment by ASharpPen** [comment]
Very well written report :)

It would seem the template application code did not get properly updated to take into account that the spawner indexes would no longer necessarily match their assigned ids. This causes the EvilShadow to get the changes intended for the vanilla Seeker spawner, and the vanilla spawner gets no changes.

This should be fixed in the upcoming release.

**Comment by nbusseneau** [comment]
Confirm the bug is fixed on my end with 1.2.14. Thanks!
